version: '3.7'

services:
  mongo:
    image: mongo:5.0.10
    container_name: mongo
    env_file:
      - .env 
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
     - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    env_file:
      - .env 
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASS}
      - ME_CONFIG_MONGODB_URL=${MONGO_URL}
  server:
    build: .
    container_name: server
    depends_on:
      - mongo 
    ports:
      - 5000:5000
    env_file:
      - .env 
  